---
- import_tasks: nginx-official-repo.yml
  when: nginx_official_repo == True
- import_tasks: installation-packages.yml
  when: nginx_installation_type == "packages"
- import_tasks: installation-source.yml
  when: nginx_installation_type == "source"
- import_tasks: ensure-dirs.yml
- import_tasks: remove-defaults.yml
  when: not keep_only_specified
- import_tasks: remove-extras.yml
  when: keep_only_specified
- import_tasks: remove-unwanted.yml
- import_tasks: configuration.yml

- name: Start the nginx service
  service: name={{ nginx_service_name }} state=started enabled=yes
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
  tags: [service,nginx]
